### ISSUE TITLE
Utf8Json doesn't serialize datatables

### ISSUE THREAD

**Issue by isabr85** [Cryptisk/Utf8Json#21]
My service built with .NET Core 3.1
Once I am trying to serialize a datatable I'm getting an exception from utf8json.

Are you aware about this issue?
Is that something that could be resolved in the future?

**Comment by cryptisk-grs** [comment]
We don't support serializing `DataTable` and if we did, it would likely be horrendously slow. You should instead transform the data from your DT to a list/array of an object from your data model that will hold that data instead, that'll we'll serialize.
