### ISSUE TITLE
DictionaryFormatterBase Serialize action ignoring FormatterResolver

### ISSUE THREAD

**Issue by isabr85** [Cryptisk/Utf8Json#27]
I am using DictionaryFormatter for execution of serialization within a custom formatter that I wrote.

```
public sealed class CustomTypeFormatter : IJsonFormatter<MyCustomType>
{
     ...
     public void Serialize(ref JsonWriter writer, DataTable value, IJsonFormatterResolver formatterResolver)
     {
          Utf8Json.Formatters.DictionaryFormatter<string, object> formatter = new Utf8Json.Formatters.DictionaryFormatter<string,object>();
          formatter.Serialize(ref writer, myDictionary, formatterResolver);
     }
     ...
}
```

Inside Serialize method I am instantiating a dictionary formatter and in the next line I am calling Serialize action of the formatter that was just created and passing formatterResolver which was given as method parameter. My formatterResolver contains a definition to use Camel-Case naming.

When I am executing my code, my dictionary is actually serialized, but no Camel-Case naming applied on dictionary's keys.
Then I tried to investigate the code, and I noticed that inside 'DictionaryFormatter.cs' file, line 38 (and 51) keyFormatter is executing 'SerializeToPropertyName' method, which receives the formatterResolver, 

But it seems that SerializeToPropertyName is not using the formatterResolver at all:

```
public void SerializeToPropertyName(ref JsonWriter writer, string value, IJsonFormatterResolver formatterResolver)
{
     writer.WriteString(value);
}
```
So, the property name is being written regardless to the formatterResolver definitions.
I am confused, why formatterResolver been sent all the way up to this method but is not being used? 
Am I missing something?

**Comment by zcsizmadia** [comment]
What happens if you create the formatter via formatterResolver and not directly with a new? GetFormatter will cache the created  formatter, so it is not created every time.

```cs
public sealed class CustomTypeFormatter : IJsonFormatter<MyCustomType>
{
     ...
     public void Serialize(ref JsonWriter writer, DataTable value, IJsonFormatterResolver formatterResolver)
     {
         var formatter = formatterResolver.GetFormatter<Dictionary<string,object>>(); // <- type of myDictionary
         formatter.Serialize(ref writer, myDictionary, formatterResolver);
     }
     ...
}
```

**Comment by zcsizmadia** [comment]
After checking the source code, the IJsonFormatterResolver does not have any concept of the nameMutator, what the resolvers use for the different naming flavors. Btw if the default string formatter would do that conversion, in that case all strings would be converted to CamelCases.

Th DictionaryFormatterBase gets a formatter based on the key type, (in your case string)
```
var keyFormatter = formatterResolver.GetFormatterWithVerify<TKey>() as IObjectPropertyNameFormatter<TKey>;
```

1. You can create a CustomDictionaryFormatter<string,object> and do the the conversion for the key. This seems to be a little bit nasty, since you have to copy paste most of the DictionaryFormatterBase from the source and replace ```keyFormatter.SerializeToPropertyName(ref writer, item.Key, formatterResolver);``` with the camel casing.
2. You replace the string key type with your custom type derived from string, and create a simple formatter for that.

**Comment by zcsizmadia** [comment]
Found a cool solution :) SInce most DictionaryFormatters are sealed, you must inherit from the Base, but instead of touching the serializer functions, just override the enumerator, and do the Key conversion there.


```cs
public sealed class DictionaryCamelCaseKeyFormatter<TValue> : DictionaryFormatterBase<string, TValue, Dictionary<string, TValue>, IEnumerator<KeyValuePair<string, TValue>>, Dictionary<string, TValue>>
{
    protected override void Add(ref Dictionary<string, TValue> collection, int index, string key, TValue value)
	{
		collection.Add(key, value);
	}

	protected override Dictionary<string, TValue> Complete(ref Dictionary<string, TValue> intermediateCollection)
	{
		return intermediateCollection;
	}

	protected override Dictionary<string, TValue> Create()
	{
		return new Dictionary<string, TValue>();
	}

	protected override IEnumerator<KeyValuePair<string, TValue>> GetSourceEnumerator(Dictionary<string, TValue> source)
	{
		foreach(var item in source)
                {
			yield return KeyValuePair.Create(
				CultureInfo.CurrentCulture.TextInfo.ToTitleCase(item.Key), // CamelCase conversion happens here !!!
				item.Value);
		}
	}
}
```

And then create a custom resolver:

```cs
...
var customResolver = CompositeResolver.Create(
	new IJsonFormatter[]
	{
		new DictionaryCamelCaseKeyFormatter<object>()
	},
	new IJsonFormatterResolver[] {
		StandardResolver.CamelCase
	});

JsonSerializer.ToJsonString(data, customResolver);
...
```

**Comment by isabr85** [comment]
Thank you for your solution.
